### ISSUE TITLE
Packer boxes mapping 

### ISSUE THREAD

**Issue by olelukoje** [bwsw/rt-motion-detection-opencv-python#1]
I've made some experiments with your code and found out an error in `packer.py`:
```
box_map.append((b, (x, y, x + w, y + h), (rid[1], rid[0], rid[3], rid[2])))
``` 
should be
``` 
box_map.append((b, (x, y, x + w, y + h), (rid[0], rid[1], rid[2], rid[3])))
```
for correct mapping with original box coordinates.

**Comment by bwsw** [comment]
@olelukoje Looks like I twisted my brain.
