### ISSUE TITLE
Pip Install

### ISSUE THREAD

**Issue by Odianosen25** [bwsw/rt-motion-detection-opencv-python#11]
Hello,

Thanks for this nice code. Any plans to make it easily pip install-able? Will like to use it within a docker environment, but as it is now, for some reasons being difficult for me to install.

Tried using 
```
pip3 install git+https://github.com/bwsw/rt-motion-detection-opencv-python
```

tells me
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/bwsw/rt-motion-detection-opencv-python
  Cloning https://github.com/bwsw/rt-motion-detection-opencv-python to /tmp/pip-req-build-78890b7e
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/motion_detector_optimization.egg-info
    writing pip-egg-info/motion_detector_optimization.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/motion_detector_optimization.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/motion_detector_optimization.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/motion_detector_optimization.egg-info/SOURCES.txt'
    error: package directory 'opti_module' does not exist

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-78890b7e/
```

This message pops up both in Windows and Ubuntu

Kind regards

**Comment by bwsw** [comment]
@Odianosen25 hi. As the code builds some C-files, it requires the build dependencies like 'build-essential' for Ubuntu/Debian. So, I don't think it will work smoothly without the additional tools and packages installed.

**Comment by Odianosen25** [comment]
@bwsw thanks for the response. I already had `build-essential` installed, but it seems its looking for this `opti_module` in the `setup.py`, which I don't know where it resides. Searched online and still no clue what it is.

Thanks

**Comment by bwsw** [comment]
@Odianosen25 
Well, looks like it's not about the real absence of the module, but about the directory from which the build happens. Unfortunately, I don't have the quick fix for that.
