### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Odianosen25** [bwsw/rt-motion-detection-opencv-python#13]
Hello @bwsw,

I will like to use some of your functions within another project of mine, but I am trying to understand how they work; especially the [pack](https://github.com/bwsw/rt-motion-detection-opencv-python/blob/master/bounding_boxes/__init__.py#L33). I do understand it takes a bunch of rects which indicates the different contours found as motion, and combines them based on distance right?

I found myself in similar issues when building a project, and though I used non-maxima suppression to combine those that overlap, it didn't work for close ones and still led to having lots of disjointed contours. Looking at your `pack` code, I believe it will solve the issue for me.

So please I am  asking if there is a way to explain  a bit more what is passed into it. As I can't seem to get what the `bins` is all about. Then why the extra [copy_images](https://github.com/bwsw/rt-motion-detection-opencv-python/blob/master/packer.py#L19) function.

I am sorry I don't really understand C code, so why the extra confusion. I know its a lot to ask, but understanding it will really help.I have spent a lot of  time trying to, but to no avail.

Kind regards

**Comment by bwsw** [comment]
@Odianosen25 
Hi, pack is a knapsack problem solver reimplemented in C. 
You can use pure python implementation like https://github.com/secnot/rectpack

**Comment by bwsw** [comment]
Take a look here:
https://github.com/bwsw/rt-motion-detection-opencv-python/blob/de72a838f8f41f14b93fb504a982f68e1a9c2f46/packer.py
