### ISSUE TITLE
Exception has occurred: IndexError list index out of range

### ISSUE THREAD

**Issue by peijason** [bwsw/rt-motion-detection-opencv-python#14]
@bwsw Hi, thank you for providing such a tool. However, there seems to be a bug for the lambda function you are using.

```console
Exception has occurred: IndexError
list index out of range
  File "....../motiondetector.py", line 42, in <lambda>
    box_filter=lambda b: ((b[2] - b[0]) * (b[3] - b[1])) > 1000,
  File "....../packer.py", line 11, in pack_images
    if box_filter(b):
  File "....../motiondetector.py", line 37, in <module>
    results, box_map = pack_images(
```

It looks like when **b** is empty,  **b[0]**, **b[1]**, **b[2]**, **b[3]** are just meaningless..
I'm moving out the **lambda** function...

Cheers
Pei

**Comment by smandal94** [comment]
Change: 
--> boxes = detector.detect(frame)
To:
--> boxes, _ = detector.detect(frame)

**Comment by DispooL** [comment]
> Change:
> --> boxes = detector.detect(frame)
> To:
> --> boxes, _ = detector.detect(frame)

Thank you!
