### ISSUE TITLE
undefined symbol: PyInt_AsLong

### ISSUE THREAD

**Issue by fshsweden** [bwsw/rt-motion-detection-opencv-python#15]
I thought this lib was for Python3, but the C-code references PyInt_AsLong which is deprecated. Can you clarify?

**Comment by bwsw** [comment]
Hi, it's built for Python 3.6, where PyInt_AsLong, AFAIK, looks like it's deprecated in 3.7.

**Comment by fshsweden** [comment]
Sure? Can you point to the documentation  page, because I can't find it for 3.6 or any other 3.X version.  There is however a suggested way of solving this issue by something on the lines of:

if PY_MAJOR_VERSION >= 3
    #define PyInt_FromLong PyLong_FromLong
endif

**Comment by bwsw** [comment]
@fshsweden I'll try to add that and build.

**Comment by bwsw** [comment]
@fshsweden Hi, I've updated the project for Python3 support. Now it builds fine and works properly under Python3.

**Comment by fshsweden** [comment]
Yes now it compiles without problems. Thx.
