### ISSUE TITLE
Is it possible to use without numba?

### ISSUE THREAD

**Issue by fshsweden** [bwsw/rt-motion-detection-opencv-python#17]
I would like to try this lib on a Raspberry Pi 3, and as far as I see it, numba on that platform requires either that I use some special distribution "berryconda" which I never heard of before, or a very complicated compilation process. Is this lib strictly needed, and would it be possible to make a version that doesnt use it?

**Comment by bwsw** [comment]
@fshsweden well, if you remove every `@jit(nopython=True)`, then you can remove numba dependencies, but it will be slower.
