### ISSUE TITLE
Error when building the project

### ISSUE THREAD

**Issue by Joldiazch** [bwsw/rt-motion-detection-opencv-python#19]
when I run the **_make_** command  on wondows 10 I get the following errors:

Makefile:44: warning: ignoring prerequisites on suffix rule definition
gcc -c src/scanner.c -o src/scanner.o -W -Wall -Werror -Wextra -fPIC -O3 `pkg-config --cflags python3` -Isrc -I`python3 -m site --user-site`/numpy/core/include
gcc: error: `pkg-config: No such file or directory
gcc: error: python3`: No such file or directory
gcc: error: site: No such file or directory
gcc: error: unrecognized command line option '--cflags'
gcc: error: unrecognized command line option '-m'
gcc: error: unrecognized command line option '--user-site`/numpy/core/include'
make: *** [Makefile:44: src/scanner.o] Error 1

**Comment by PikaPikaPickles** [comment]
Did you found a solution of the problem?
Please? can you share it?

**Comment by qsek1** [comment]
copy the numpy folder from \venv\Lib\site-packages\numpy\core\include to the \src folder where scanner.c is located.
It should look like \src\numpy\arrayobject.h
