### ISSUE TITLE
Getting Segmentation Fault 11 

### ISSUE THREAD

**Issue by hneiraf** [bwsw/rt-motion-detection-opencv-python#8]
Hi,

I'm trying to test your algorithm, on mac os x, compiled the c parts successfully, Python 3.7.7
All required libraries installed.

I'm executing the program but I'm always getting segmentation fault 11.

/usr/local/bin/python3.7 /Users/XXX/PycharmProjects/rt-motion-detection/sample.py
StdDev: 0.0000 Mean: 6.9940 Boxes found:  0
StdDev: 0.8925 Mean: 6.1015 Boxes found:  0
StdDev: 0.8986 Mean: 5.7298 Boxes found:  0
StdDev: 0.7841 Mean: 5.6745 Boxes found:  0
StdDev: 0.7151 Mean: 5.6046 Boxes found:  0
StdDev: 0.6545 Mean: 5.5836 Boxes found:  0
StdDev: 0.6067 Mean: 5.5707 Boxes found:  0

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

UPDATE:

Added import faulthandler; faulthandler.enable()

I'm getting this:

Current thread 0x000000011bcee5c0 (most recent call first):
  File "/Users/XXX/PycharmProjects/rt-motion-detection/bounding_boxes/__init__.py", line 23 in scan
  File "/Users/XXX/PycharmProjects/rt-motion-detection/detector.py", line 119 in __get_movement_zones
  File "/Users/XXX/PycharmProjects/rt-motion-detection/detector.py", line 109 in detect
  File "sample.py", line 32 in <module>
Segmentation fault: 11

I haven't changed the default values.

Hope you guys can give me a hand.

Best,

Hugo

**Comment by bwsw** [comment]
@hneiraf Hi, could you please provide me with the video source which gives you a segfault?
BTW, we only tested in Linux.

**Comment by bwsw** [comment]
@hneiraf also, try running with `group_boxes=False`. Do things change?

**Comment by hneiraf** [comment]
Hi,

I tried with my mac book pro webcam, but also with the video used in your demo, I downloaded it. Same issue. I also tried group_boxes = False, and nothing.

Best and thank you for your quick reply,

Hugo Neira

Enviado desde mi iPhone

**Comment by hneiraf** [comment]
I'm still getting the same error.
I'm working with python 3.7.7 and last version of all required libraries, something related to this?

Best,

Hugo

**Comment by hneiraf** [comment]
This is what I'm getting:

StdDev: 0.0000 Mean: 1.3139 Last: 1.3139 Boxes found:  0
StdDev: 0.1974 Mean: 1.1165 Last: 0.9191 Boxes found:  0
StdDev: 0.2242 Mean: 1.0064 Last: 0.7861 Boxes found:  0
StdDev: 0.1952 Mean: 0.9945 Last: 0.9589 Boxes found:  0
StdDev: 0.1751 Mean: 1.0010 Last: 1.0269 Boxes found:  0
StdDev: 0.1601 Mean: 1.0051 Last: 1.0259 Boxes found:  0
StdDev: 0.1552 Mean: 1.0239 Last: 1.1368 Boxes found:  0
Fatal Python error: Segmentation fault

Current thread 0x00000001149ea5c0 (most recent call first):
  File "/Users/XXX/PycharmProjects/rt-motion-detection/bounding_boxes/__init__.py", line 25 in scan
  File "/Users/XXX/PycharmProjects/rt-motion-detection/detector.py", line 119 in __get_movement_zones
  File "/Users/XXX/PycharmProjects/rt-motion-detection/detector.py", line 109 in detect
  File "/Users/XXX/PycharmProjects/rt-motion-detection/sample.py", line 40 in <module>

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

**Comment by SylvainGarrigues** [comment]
Same here, seg fault on macOS.

**Comment by bwsw** [comment]
@SylvainGarrigues, @hneiraf I don't have MacOS to test and fix it. Please do it with your own environments and send a PR here.

**Comment by markkorput** [comment]
I'm also getting the seg fault (also on macOS), I've been able to narrow it down to the ```Py_BuildValue``` call in the below line in scanner.c. Haven't been able to solve it, but seems like on my machine Py_BuildValue with ints always segfaults, though floats sometimes work... dunno, not familiar with this kind of python/c interoperability.

```c
PyList_Append(boxes, Py_BuildValue("(iiii)", c_min, r_min, c_max, r_max));
```
