### ISSUE TITLE
build in anaconda environment

### ISSUE THREAD

**Issue by rh66** [bwsw/rt-motion-detection-opencv-python#9]
Hello,
Could someone provide instruction about how to build it in anaconda environment, in windows 10? After clone the directory locally, the command 'python setup.py build' ends with error:

running build
error: [WinError 2] The system cannot find the file specified

Does that mean the setup.py is not calling conda-build? then how to build?

Thanks

**Comment by bwsw** [comment]
Windows support is not expected. Thanks.
